### ISSUE TITLE
broken link from neurosynth to neurovault

### ISSUE THREAD

**Issue by arielletambini** [neurosynth/neurosynth-web#103]
It appears that the link from a neurosynth decoding analysis back to an original map in neurovault is broken (at least in this one case).

For example, from here: http://neurosynth.org/decode/?neurovault=JOYXPMRX-26012

when I click on the link which should go back to the original neurovault image, the link is incorrect. It currently goes to: http://neurovault.org/images/JOYXPMRX-26012 (which does not exist)

but instead should go to: http://neurovault.org/collections/JOYXPMRX/images/26012/

**Comment by vsoch** [comment]
Is this a previously private collection? If the link being sent is a random mix of characters / numbers, my first guess is that it might be a previously private and now public, in which case (the neurosynth default) of going back to `neurovault.org/images/{{id}}` doesn't work. @tyarkoni I think you would want to generate that url custom based on its format with a regular expression, either just an image number, or some weirdo string of stuff with a dash and number. I might be totally off, this is just my first instinct looking at the image!

**Comment by vsoch** [comment]
dun dun!! [Here is the booger](https://github.com/neurosynth/neurosynth-web/blob/e1c6d9e1e203edc6d91ed7c010aa74dd17cdb3c6/nsweb/templates/decode/show.html.slim#L11)!
