### ISSUE TITLE
Associations table not loading

### ISSUE THREAD

**Issue by mquinci** [neurosynth/neurosynth-web#124]
I have been using your "Associations with meta-analysis maps" table under Locations for some analyses. Over the last three days, the table does not load when I input a coordinate (though the "studies reporting activation" table does load). Could you please advise?

Thank you,
Milena

**Comment by PAmcconnell** [comment]
@tyarkoni not sure if this thread pertains to the website but this issue still stands. All of the coordinate based searches work except for the "associations" table. It freezes while loading coordinate location meta results and returns to the main home screen. Is the website no longer being maintained?  Cheers,
Patrick

**Comment by PAmcconnell** [comment]
> I have been using your "Associations with meta-analysis maps" table under Locations for some analyses. Over the last three days, the table does not load when I input a coordinate (though the "studies reporting activation" table does load). Could you please advise?
> 
> Thank you,
> Milena

@mquinci have you discovered anything re: this issue? Could it be a java thing?

**Comment by tyarkoni** [comment]
Should be fixed now.
