### ISSUE TITLE
Add database models for Analysis and Inclusion (2)

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#25]
In preparation for having the server keep track of analyses, the back-end will need to be modified to keep a record of every analysis a user runs on the platform. All analysis-related models should be housed in models/analyses.py. We will need to extend/implement two classes:

* An Analysis model that represents a single analysis, including all metadata describing the analysis. There is a rudimentary implementation of this that contains fields for name, description, uuid, and IP address, standard timestamps, as well as a foreign key linking the table to the User model (so we can track which User created the Analysis). The name and description fields are provided by the user. The IP address indicates the current IP of the user when requesting the analysis. The uuid is a hash generated at analysis creation time that serves as the URL for all subsequent requests of that analysis. I.e., each analysis has a route of the form: http://neurosynth.org/analyses/102831acd10303 (the specific length and nature of the hash isn't important, it just needs to be unguessable and unlikely to cause collisions).

In addition to these fields, we will probably want to add others as the need arises. For example, it may make sense to have an n_studies field that tracks the number of studies included in the analysis (even though that can always be computed dynamically by counting the associated Study records). We might also want a 'status' field that indicates whether the analysis has already been run or not (or maybe just an "executed" boolean).

* An "Inclusion" model that serves as the many-to-many join table for Analysis <--> Study. The Study model probably won't need to be modified at all to make this work. The basic Inclusion model itself is already implemented, though untested.

**Comment by skept** [comment]
@tyarkoni What does the frequency field in the Frequency model represent?

I'm still getting up to speed on SQLAlchemy. I'm getting the below error when I try to create a new CustomAnalysis model. Any ideas? I'm looking into it myself but you can probably figure it out much quicker:

```
---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
<ipython-input-23-f620f9252959> in <module>()
      1 u = unicode(uuid.uuid4())[:18]
----> 2 c = CustomAnalysis(uuid=u)

<string> in __init__(self, **kwargs)

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/orm/instrumentation.pyc in _new_state_if_none(self, instance)
    322                 _new_state_if_none(instance)
    323         else:
--> 324             state = self._state_constructor(instance, self)
    325             setattr(instance, self.STATE_ATTR, state)
    326             return state

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.pyc in __get__(self, obj, cls)
    723         if obj is None:
    724             return self
--> 725         obj.__dict__[self.__name__] = result = self.fget(obj)
    726         return result
    727 

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/orm/instrumentation.pyc in _state_constructor(self)
    156     @util.memoized_property
    157     def _state_constructor(self):
--> 158         self.dispatch.first_init(self, self.class_)
    159         return state.InstanceState
    160 

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/event/attr.pyc in __call__(self, *args, **kw)
    258             fn(*args, **kw)
    259         for fn in self.listeners:
--> 260             fn(*args, **kw)
    261 
    262     def __len__(self):

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/orm/mapper.pyc in _event_on_first_init(manager, cls)
   2691     if instrumenting_mapper:
   2692         if Mapper._new_mappers:
-> 2693             configure_mappers()
   2694 
   2695 

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/orm/mapper.pyc in configure_mappers()
   2587                 if not mapper.configured:
   2588                     try:
-> 2589                         mapper._post_configure_properties()
   2590                         mapper._expire_memoizations()
   2591                         mapper.dispatch.mapper_configured(

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/orm/mapper.pyc in _post_configure_properties(self)
   1692 
   1693             if prop.parent is self and not prop._configure_started:
-> 1694                 prop.init()
   1695 
   1696             if prop._configure_finished:

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/orm/interfaces.pyc in init(self)
    142         """
    143         self._configure_started = True
--> 144         self.do_init()
    145         self._configure_finished = True
    146 

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/orm/relationships.pyc in do_init(self)
   1547     def do_init(self):
   1548         self._check_conflicts()
-> 1549         self._process_dependent_arguments()
   1550         self._setup_join_conditions()
   1551         self._check_cascade_settings(self._cascade)

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/orm/relationships.pyc in _process_dependent_arguments(self)
   1603                 util.to_column_set(self.remote_side))
   1604 
-> 1605         self.target = self.mapper.mapped_table
   1606 
   1607     def _setup_join_conditions(self):

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.pyc in __get__(self, obj, cls)
    723         if obj is None:
    724             return self
--> 725         obj.__dict__[self.__name__] = result = self.fget(obj)
    726         return result
    727 

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/orm/relationships.pyc in mapper(self)
   1520         if util.callable(self.argument) and \
   1521                 not isinstance(self.argument, (type, mapperlib.Mapper)):
-> 1522             argument = self.argument()
   1523         else:
   1524             argument = self.argument

/Users/pouya/projects/venv/ns/lib/python2.7/site-packages/sqlalchemy/ext/declarative/clsregistry.pyc in __call__(self)
    281                 "adding this relationship() to the %r class after "
    282                 "both dependent classes have been defined." %
--> 283                 (self.prop.parent, self.arg, n.args[0], self.cls)
    284             )
    285 

InvalidRequestError: When initializing mapper Mapper|Frequency|frequency, expression 'Study' failed to locate a name ("name 'Study' is not defined"). If this is a class name, consider adding this relationship() to the <class 'nsweb.models.frequencies.Frequency'> class after both dependent classes have been defined.
```

**Comment by tyarkoni** [comment]
The frequency field stores weights or loadings--effectively the strength of association between analyses and studies. For CustomAnalyses, it won't mean anything (at least initially), so it should just be set to 1. 

The error might be caused by failure to import the Study model? If not, paste the full model code in the gist.

Note that there should already have been a working CustomAnalysis model in models/analyses.py that just needs fields added.

**Comment by skept** [comment]
Ok, added models/analyses.py to the gist.

**Comment by tyarkoni** [comment]
Oh, hah--I'm missing import statements in some of the models. I guess it's never raised an exception before because I only ever instantiate or call the models in contexts where the appropriate models are already explicitly imported (e.g., in the database_builder script). For now you can just import all of the models to be safe (take all the import nsweb.model.* statements from the database_builder script). I'll push an update in a sec that should fix this.

**Comment by tyarkoni** [comment]
Actually, if I add import statements in the model files, I get circular imports (and I now recall that I explicitly removed the import statements to avoid this). I think the best way out of this is actually to import all of the models at one shot within in the app. I was trying to maintain strict modularity, but there's really no good reason for that here. For now, just use the import statements in database_builder and see if that works; I'll fix this up in a commit later tonight or tomorrow.

**Comment by skept** [comment]
Ok, I still haven't got it to work from the external shell but I'll look into it later. It's working fine from inside the controller module and I can debug by setting breakpoints. I don't think we have a bug here, so you can ignore this, at least for now. Thanks for looking into it.
