### ISSUE TITLE
Create analysis management page (6)

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#29]
Create a new page at neurosynth.org/analyses that allows the currently logged in user to view and manage all of their existing analyses.

**Comment by skept** [comment]
I'm already taking care of this for custom analyses (see /analyses/custom/). Do we want term and topic analyses to also be saved and displayed in the same way? Technically that's already possible although the usability could be improved - the user would have to select all studies in a term/topic analysis and then go to /analyses/custom and save it.

**Comment by skept** [comment]
Closing this. See /analyses/custom/. Feel free to open new tickets if there's any functionality you think is missing from this page.

**Comment by tyarkoni** [comment]
Will do, thanks! I'm reviewing it now and will probably open a few more, but obviously don't worry about getting to them before we meet.
