### ISSUE TITLE
React custom analysis code interferes with viewer

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#37]
I just pushed some code to the analysis branch that runs a custom meta-analysis and redirects to the results page. This works fine if all of the JS code for custom analyses is disabled (e.g., by commenting out custom_analyses.coffee.js in the webassets pipeline), but when the custom analysis code is enabled, none of the viewers work. As far as I can tell the issue seems to be that the app.init() call always calls fetchAll(), which assumes that all of the elements present at /analyses/custom/ (i.e., custom-list-container and active-analysis-container) exist on every page, even though they don't exist anywhere except on the analysis editing page. I think we'll need to add some checks to see if fetchAll() (and any other offending methods) can be called.

**Comment by skept** [comment]
@tyarkoni Can you point me to your code? Which page do you run the custom meta-analysis from?

**Comment by tyarkoni** [comment]
See 585134c6e6d5a1. But I'm 99% sure the problem isn't with the code I committed when I opened this issue, it's that there's some conflict between something your React code is doing and my viewer code (which lives in js/nsviewer). Or rather, I suspect that probably the failure to find elements the React analysis code is looking for causes an exception, and then the JS engine never makes it to the viewer code.

**Comment by tyarkoni** [comment]
Oh, and the problem occurs on every page where the viewer is loaded, independently of whether I'm trying to run a custom analysis or not (e.g., if you go to neurosynth/terms/emotion, the images never load under the analyses branch).

**Comment by tyarkoni** [comment]
I figured it out. It turns out that the xtk.js library, which I use to load the images, defines a function called ce(). In your custom_analysis code, you're assigning React.createElement to var ce for convenience, which then causes everything to break when xtk tries to load the images.

Since I don't want to tamper with the xtk library, could you rename ce to something else? Actually, probably even better would be to just keep using the full function name under the React namespace. More typing, but less clutter. :) Thanks!

**Comment by tyarkoni** [comment]
Just made those changes. Closing this.

**Comment by tyarkoni** [comment]
Reopening this because somehow the ce assignment that mucked things up reappeared in c785960a6739c3 in custom_analyses.coffee.js. Probably a merge conflict. @skept, I'll push a fix, but make sure to merge it before you do anything else.
