### ISSUE TITLE
Add brainspell integration to /studies

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#47]
Per discussion with @r03ert0, add a tab on each study's page displaying the current brainspell representation of the study. Also add a link to brainspell encouraging users to edit/annotate studies that have QC issues.

**Comment by r03ert0** [comment]
cool !!! :D

**Comment by tyarkoni** [comment]
Closing in favor of eventual brainspell-neo/metacurious integration (which will likely be a while).
