### ISSUE TITLE
allow unthresholded image download

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#50]
Currently there's no way to download unthresholded forward and reverse inference z-maps. We should add the facility to retrieve unthresholded maps for the special case where the requested image is a meta-analysis map in a format we understand (i.e., with a filename like *pAgF_z_FDR...). Probably the easiest way to handle this right now is to add an 'unthresholded_filename' attribute to the AnalysisImage model that returns the right filename.

**Comment by vsoch** [comment]
:+1: 

yes yes yes this is very good! :L)

**Comment by tyarkoni** [comment]
Added  in 40578ca80cd03fbfe12a. Default (i.e., FDR-corrected images) can now be downloaded like so:

http://neurosynth.org/analyses/terms/emotion/images/reverse

And unthresholded variants can be requested like so (if available):

http://neurosynth.org/analyses/terms/emotion/images/reverse?unthresholded

**Comment by janfreyberg** [comment]
It would be great if this could be added to the FAQs as well, or as a link in the map interface?
