### ISSUE TITLE
"discard current selection" button clears everything

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#54]
On the custom analysis page, when the user clicks the "discard current selection" button, the whole selection interface disappears, and the user has to navigate to a different page and select at least one study to make it reappear. We probably want to keep the study selection interface in place and just clear the "selected studies" table.

**Comment by skept** [comment]
@tyarkoni I think I picked a poor name for that button. What I meant for it to do is to discard the current headless (i.e. never saved to the server - only in the local storage) analysis from the local storage. That way when you visit the custom analysis page you don't see anything previously loaded. Your suggestion of keeping the study selection interface makes sense. Thinking about it more, currently the only way to get the study selection interface on the custom analysis page is to either clone an existing saved study or to select a few studies on other pages and then coming back to the custom analysis page. It probably makes sense to always display a blank analysis if the user is visiting the custom analysis page, with the only exception being when a previously saved study has already been loaded into local storage.

**Comment by tyarkoni** [comment]
Yep, that sounds like the way to go. Upon first loading the page, I think we should check to see if an analysis exists, and if not, create a blank one (which I presume will trigger the interface loading). Then the discard button can just replace whatever the current analysis is with a new blank one and achieve the same thing.

**Comment by skept** [comment]
Took care of this as discussed above.
