### ISSUE TITLE
Connect "run" button to right url

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#57]
At this point I think the "run" custom analysis button can be connected to the back-end. All the button has to do is load this URL:

/analyses/custom/run/{uuid}

...which will run the meta-analysis (or not, if it's already been run) and then redirect to the analysis viewer page.

**Comment by skept** [comment]
I'm running redis-server on my laptop but visiting /analyses/custom/run/<uid> doesn't just sends the server spinning forever without returning any response. I'm new to Redis. Any idea what's going on?

**Comment by tyarkoni** [comment]
It's probably a celery issue. I haven't documented the celery configuration anywhere, and the workers need to be pointed to the right place. I suggest skipping this for now (or just implement the link, and I'll test it out later), and I'll work on this later if I have a chance.

**Comment by skept** [comment]
You're right. I wasn't running celery. Ok, I'll skip this for now. I have celery installed. If you know the command to run the celery server send it to me and I'll try it out.
