### ISSUE TITLE
Load analysis button should be enabled as soon as user makes any change to study list

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#59]
Say a user loads an existing analysis, but then edits the list of studies. At that point, the "load" button should be re-enabled for the currently loaded analysis, because the user may want to revert to the original list of studies. Actually, I think the Load button can probably always be enabled; I'm not sure there's a reason to disable it. What should probably happen though is that if the user clicks on Load and there are unsaved changes, a dialog window should pop up and ask for confirmation before the load goes through.

**Comment by skept** [comment]
That makes sense. I made it so the Load button remains enabled at all times. If there are unsaved changes the user is warned via an alert dialog when trying to load the same or another study.
