### ISSUE TITLE
replace "no analyses" message on custom page load with something more accurate

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#61]
When a user first visits /analyses/custom while logged in, they initially see a message saying that "you have no saved custom analyses". Once the interface loads, it goes away, but that can take a while given the amount of data being sent. Let's replace the current message with something like "Loading interface..."

Actually, if it's a small tweak, it would be even better to do the data loading after the interface itself has loaded. But if that would be complicated to change because of the way the React code loads, then let's just leave it as is.

**Comment by skept** [comment]
Took care of the copy update. I also made it so most of the interface (including the list of saved analyses) is loaded before I fetch the study details from the server. The page now loads much faster, although it still takes a couple of seconds before the study tables get populated. Fetching the list of all study details from the server is by far the slowest part. I opened a separate ticket to improve this by caching the results.
