### ISSUE TITLE
Hide selection interface on datatables by default

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#63]
Not sure what the best way to handle this is, so let's talk about it before you change anything, but I think we should either (a) only show the selection interface to logged-in users (to avoid confusing people who don't know what they're selecting when they first encounter it), or (b) disable the interface until the user chooses to turn it on (via a switch on the custom analyses page, or maybe we need to introduce a site-wide settings page at this point).

**Comment by skept** [comment]
I like option (a) because it's simpler. We can also add copy somewhere around any selectable table explaining that selections can be saved/edited on the custom analyses page.

**Comment by tyarkoni** [comment]
Okay, let's go with (a) then. I do think down the line I'll probably want to add a global settings interface anyway, because there are already some other site-wide things that could stand to be consolidated in one place as user-level settings. But that's overkill for now. I also like the idea of adding some information to the existing interface

 Another option would be to have a simple hide/show toggle for the interface that's hidden by default, so that the user has to click on a button on the right side called "select studies" or something in order to turn on the selection UI. But for now let's go with (a).

**Comment by skept** [comment]
@tyarkoni Frustrated by slim parse errors I switched to plain HTML for the /studies page. Hope that's ok. I implemented (a) for the Studies page. Let me know if it looks ok and I'll do the same thing for the tables on the _terms_ and _locations_ pages too.

**Comment by tyarkoni** [comment]
Sure, that's fine.

Changes look good, but it seems like only the buttons are hidden; the user can still select rows in the table, and they probably won't understand what that means. I think we should disable all selection-related UI elements unless users are logged in. Also, if you're not logged in, right now you get this message at the top of the page:

> You must be signed in to access '/api/custom/all/'.

I think we should remove that, and instead, maybe modify the text currently on the page so that right after this:

> The table below contains a listing of all studies currently included in the Neurosynth database, representing a significant fraction of the current fMRI literature. New studies are added at regular intervals.

...we add something like "If you'd like to select individual studies from the table below and conduct custom online meta-analyses, please log in." (where 'log in' is a link to the login page).

**Comment by skept** [comment]
Ok, I fixed those on the Studies page. I'll take care of the other page too.

**Comment by skept** [comment]
@tyarkoni The locations page is quite a bit longer so I've been trying to give slim another chance before giving up and manually converting the whole page to HTML. I'm getting a slim parse error on line 54 and thought it'd be quicker to ask you for help. Can you check out the above commit and visit the /locations/ page? You may want to disable the cache decorator on the controller function to see the page refresh.

**Comment by tyarkoni** [comment]
Yeah, that issue caused me no end of grief until I figured out what was going on. Basically slimish-jinja doesn't like having empty tags on a single line (here the table tags have attributes, but they don't enclose anything). You just need to prepend those lines with a % and it'll work.

The slimish-jinja README does actually cover all possible situations, as far as I've been able to tell, but the documentation could certainly stand to be clearer:

https://github.com/thoughtnirvana/slimish-jinja2

In hindsight it probably wasn't a good idea to use it in the first place, but at this point I don't think it's worth investing the time to re-write everything in jinja (and then we'd have to close every tag! ugh!). So let's live with the growing pains. But feel free to ask if you run into any other issues.

**Comment by tyarkoni** [comment]
Just pushed a fix to the analyses branch.

**Comment by skept** [comment]
Ok, thanks. Yeah, the documentation could definitely be improved. I did spend a good bit of time going through it. 

Any idea how to use an inline _if_ statement in slim? I.e. something like:

    table#location_studies_table.table{% if user.is_authenticated() %}selectable-table{% endif %}.table-hover

**Comment by skept** [comment]
Btw, I use Pycharm which automatically closes HTML tags as you type them. I'm pretty sure there are similar plugins for Sublime.

**Comment by tyarkoni** [comment]
I think the constraint here is jinja rather than slimish-jinja per se. Haven't tried it, but per an SO post this might work:

{{ 'Update' if files else 'Continue' }}

Yeah, Emmet does that in Sublime Text, though I still find dealing with the tags kind of annoying. But if I were writing this code today, that's probably what I'd do. :)

**Comment by skept** [comment]
Ok, I'll give that a try. With jinja and plain HTML this is currently working on the studies page:

    <table class="table table-hover {% if current_user.is_authenticated() %}selectable-table{% endif %}"
                   id="studies_table">

Agree it's not worth porting things over to plain HTML at this point, although it may be hard to resist the temptation next time I hit a cryptic slim parse error :-)
