### ISSUE TITLE
Implement permissions for custom analyses

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#67]
At the moment, all custom meta-analyses are both private and public. They're private in the sense that users can't access other users' analyses via the /custom interface (is that correct, @skept?), but they're public in that once a meta-analysis has been run, the results can be viewed by anyone so long as the uuid of the analysis is known.

Right now this is a reasonable approach, because the uuids of custom analyses aren't discoverable. However, in future (i.e., beyond the initial public release of custom analyses), we're going to want a more flexible model that allows users to (a) flag whether an analysis is discoverable or not (we probably won't allow truly private analyses, at least for the time being);  (c) search for public analyses based on name/description/included studies/image content; and (c) view and clone (but not edit!) other people's discoverable analyses.

We'll probably need to add a client-side checkbox of some kind that binds to a 'public' field in the CustomAnalysis model. As discussed in #65, we'll also need to handle loading of other people's analyses encoded in url fragments. Lastly, we'll need to add a listing/search interface for custom analyses. This should probably be located at /analyses/custom/, actually, which means that the current interface will probably need to move somewhere else---perhaps /analyses/custom/edit (with a prominent link from the custom analysis index page). That way non-logged in users will be able to navigate/search custom analyses without grappling with the editing interface.

**Comment by skept** [comment]
@tyarkoni That's correct. Currently the user can't access anyone else's analyses without knowing the analysis ID.

Here's what I'm thinking of doing:

1. Add a boolean "make this analysis private" field to the custom analysis interface. This checkbox will be unchecked by default.
2. Create a new page listing all non-private custom analyses in a datatable, with hyperlinks to the existing results pages (e.g. http://neurosynth.org/analyses/custom/c1df7eb8-54fc-4f9b/)
3. When #65 is implemented we can add a "Clone this Analysis" button to analysis result page and a "Log in to Clone this Analysis" if the user isn't logged in.

Items 1 and 2 can go live before 3 is done.

**Comment by tyarkoni** [comment]
Sounds good to me!

**Comment by skept** [comment]
@tyarkoni I have an initial version of items 1 and 2 above working on the analyses branch. There's a new "Browse" option under the "Meta-analyses" menu. It's currently a static table but I'll add code to turn it into a searchable data table. 

One current limitation is that if the analysis hasn't already been run visiting the result page leads to an IndexError:

```
File "neurosynth-web/nsweb/models/analyses.py", line 48, in reverse_inference_image
return self.images[1]
```
The solution is to either not display the analyses that haven't been run yet, or have the hyperlinks in the browse table go to /custom/run/<string:uid> instead, meaning that anyone would be able to run the analysis if it hasn't been run yet. Which option do you prefer?

**Comment by tyarkoni** [comment]
Hmmm... good question. In theory, once an analysis has been saved and marked as public, there shouldn't be a reason not to show it. But it feels somehow wrong to allow a user to be the first to run/view an analysis someone else has created, and it probably makes sense not to display anything that the creator hasn't at least glanced at. So let's go with the second option for now. In practice I suspect there probably won't be many cases where people save an analysis but don't run it.

I'll try to take a look at this (and the other open issue from a couple of days ago) tonight or tomorrow, and if all looks good we can probably merge these changes into master right away.

**Comment by tyarkoni** [comment]
Sorry, I meant the first option, not the second (i.e., hiding analyses that haven't been run yet).

**Comment by skept** [comment]
@tyarkoni I took care of it but since I don't have my dev environment set up properly to run the analysis I haven't been able to test it thoroughly. Were you ever able to get a docker image working properly?

**Comment by tyarkoni** [comment]
Haven't had time to work on #43, yet, unfortunately. Hopefully soon, but no guarantees. I'll definitely test to make sure it runs properly though. (You can also always test things out on the test server at test.neurosynth.org:5001. It doesn't sync automatically, but I just pulled the analysis branch, so you can at least verify that everything works right with the code you've already committed.)

**Comment by skept** [comment]
@tyarkoni Ok, I'm getting Bad Gateway errors on the test server when I try visiting the browse page or the custom management interface. I'm suspecting it's a db migration issue. Did you try running a db upgrade on the test server?

**Comment by tyarkoni** [comment]
Oh, good catch. Just upgraded it. Should be okay now I think.

**Comment by skept** [comment]
@tyarkoni Ok, since items 1 and 2 are complete I think we can close this issue. I'll take care of item 3 as part of #65. Do you want to merge the above commit into master and push to production? Feel free to reopen if you think there's anything missing.
