### ISSUE TITLE
Add expression-based study search

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#68]
The Neurosynth core tools currently implement a PEG that allow users to search for studies using arbitrarily complex logical queries (e.g., "reward* &~ (emot* | negative)" would search for all studies that are related to reward but not emotion or negative stuff). We should add a field to the study editing interface that interfaces with the back-end to retrieve studies.

At least initially, this will be very simple (i.e., we're not going to build a GUI that allows construction of queries via multiple boxes or buttons). We'll just have a single text field for "expert search" (probably above the existing selection interface) that allows users to type in queries. There will be some documentation of valid operators, but this is intended as a power user feature, and we're not going to build in a front-end validator any time soon (i.e., if the query breaks, the user will simply be notified by the server that they did something wrong).

On the back end, I'll add an API route (requiring users to be logged in) that takes a string as input and returns a jsonified list of PMIDs. Then the client app will just need to display the selected studies (culled from the set of all studies) to the user the normal way. It will also need to handle errors sensibly (probably  just by displaying a generic "invalid query; please try again" message.

**Comment by skept** [comment]
@tyarkoni Is there already an API route that handles the above queries? If so, can you point me to it? If not, I'd be happy to build both the API backend and the frontend. The only related code that I've been able to find is: 

https://github.com/neurosynth/neurosynth/blob/master/neurosynth/base/lexparser.py

**Comment by tyarkoni** [comment]
I added an API route and celery task for this in https://github.com/neurosynth/neurosynth-web/commit/cb23323575e0e1d3c9b2c64b6ecefc95f80ca6a3. To use it, pass a query string in as the expression argument in the studies API. For example:

neurosynth.org/api/studies/?expression="language"
neurosynth.org/api/studies/?expression="reward&emot*"
neurosynth.org/api/studies/?expression="emot*&~(posit*|negat*)"

Note that the search expression should be wrapped in quotes before making the GET request, otherwise we risk having the conjunction operator misinterpreted as a new url parameter.

**Comment by skept** [comment]
Ok, to properly pass a generic expression as part of the URL we should probably encode it to a safe URI string on the client side and decode it on the server side, e.g. something like:

In Javascript:
`encodeURIComponent(expression) `

In Python:
```
import urllib 
urllib.unquote(expression)`
```

I can take care of this. It may need some tweaking to properly work with unicode characters. Checking for a blanket server error sounds reasonable.

**Comment by skept** [comment]
@tyarkoni An alpha version of this is working (see the expr-search branch). It looks like the queries are case-sensitive. Is that intended or do we want to make them case insensitive?

**Comment by tyarkoni** [comment]
Great! Will check it out soon (sorry I haven't had a chance to catch up--swamped with a grant that's due soon). We definitely want case-insensitive. Probably best to make that change on the back end, as it will also be an issue if we allow users to call the API directly later.

**Comment by skept** [comment]
Ok, I'll take care of it on the backend. Btw, any reason you're running the expression search as a celery task and not as a regular blocking request?

**Comment by tyarkoni** [comment]
Yes--most of those tasks depend on very large objects (e.g., a neurosynth Dataset instance) that can be kept in memory by the celery workers, but would take an inordinately long time to load at request time. Also, this way I can easily control the number of maximum simultaneous tasks (by setting the number of workers).

**Comment by skept** [comment]
@tyarkoni That makes sense.

FYI, looks like there's a bug in the expression search logic. In your example above these two queries return the same number of results:

reward* &~ (emot* | negative)
reward*

These two queries also return the same number of results:

reward
reward & language

Will that be a quick fix for you? If not, I can look into it. Thought I'd check with you before spending too much time on the expression search code. The front-end part of expression search is functional.

**Comment by tyarkoni** [comment]
Eep, that's not good. Thanks for catching this. I don't think you want to wade into the morass that is my ugly-ass parsing expression grammar, so probably best if I take a look. I suspect the problem actually lies in my back-end code, and not the Neurosynth code being called, because the latter has tests that cover that kind of logic. Will look into this right now...

**Comment by tyarkoni** [comment]
Looks like it's a url encoding issue. The & in the query is getting processed as a separate argument. Probably we'll need to url-encode the string on the client side and url-decode it in the backend in the get_studies_list() method in the api/studies controller. Can you make those tweaks? Thanks!

**Comment by skept** [comment]
You're right. Forgot about that! Just pushed the fix. Looks like it's working fine now. 

Do you want to add any documentation for this before pushing it to production?

**Comment by tyarkoni** [comment]
Hmm... yeah, I should probably write something. Let's hold off deploying it until I do that. I did have a look at the updates to the analyses branch from last week, and the interface looks great! I caught a minor bug though, so I'll open an issue for that before pushing to production. Also, I think the buttons could stand to be a bit bigger (at least the "edit" button--took me a while to find it).

**Comment by tyarkoni** [comment]
Never mind, looks like it was a bug in the analyses branch that was fixed in expr-search. I think I'll just go ahead and deploy the expr-search branch now and add the doc later.
