### ISSUE TITLE
Tweak buttons on custom analysis interface

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#75]
Per discussion last week, let's make some minor tweaks to the buttons on the analysis interface:

* "Clone" should be renamed to "Save As". When clicked it should behave just like the Clone button currently does, except that it should either (a) prompt the user to enter a name for the new analysis, or (b) append "(copy)" to the existing analysis name when it's cloned. Also, I think if you hit Clone after having made changes to a loaded analysis, those changes will be lost. Whereas we want Save As to retain any changes made since an analysis was loaded. (Basically, I think we want the standard semantics Save As has in most applications, e.g., MS Office.)

* Let's re-order the buttons so that they go Save, Save As, Run, and Delete, in that order.

* I think the Delete button should probably be separated from the Save/Save As/Run buttons. I would say either move it to the left side and put it under "Load" for each analysis, or insert some space between the first three buttons and the Delete button (i.e., slide it over to the right so that there's minimal chance of hitting it accidentally). I think I prefer the former, as it feels like deletion should only be something you can do to records that have already been committed to the DB.

**Comment by skept** [comment]
@tyarkoni I took care of all of the above. I went with the slightly easier option of putting some space between "Delete" and the rest of the buttons. The "Delete" button only shows up on previously saved analyses. If you still prefer I can move it under the load button.
