### ISSUE TITLE
Add help option to custom analysis UI

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#78]
I'm working on some basic documentation covering the custom analysis interface; this is the last piece before we go live. Can you add a button or tab or something somewhere conspicuous that says "Help" or some such. When clicked, it should probably pop up a browser window that contains a FAQ. The FAQ can probably just re-use or adapt the template I wrote for the site-wide FAQ (see https://github.com/neurosynth/neurosynth-web/blob/master/nsweb/templates/home/faq.html.slim). That reads the questions and answers from a json file, which I'll add shortly. If you don't think you can get to this in the next 3 - 4 days, let me know and I'll do it.

**Comment by skept** [comment]
@tyarkoni I'm going to take care of this today, unless you've already started working on it.

**Comment by tyarkoni** [comment]
Nope, haven't touched it yet, so please go ahead.

**Comment by skept** [comment]
This should be working now. You would just need a file named faq_custom_analyses.json in the same directory as faq.json.
