### ISSUE TITLE
Write tests with full coverage of code

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#9]
It would not be a terrible idea to add tests that actually work at some point in the near future.

**Comment by tyarkoni** [comment]
I'm closing this as it's a bit of a silly issue. While we're nowhere near full coverage, #bd89d9e4be32 adds a few API tests that are pretty good at narrowing down potential problems--particularly in the location and decoder functionality. Still need to work towards full coverage of the API (to say nothing about models and UI).

**Comment by chrisfilo** [comment]
Don't give up!

**Comment by tyarkoni** [comment]
I'm not giving up! I'm just, uh, "recalibrating expectations".
