### ISSUE TITLE
Clicking on "select all" on location page does nothing

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#92]
Per discussion in #80, when the "select all studies on this page" button is clicked on the studies tab in Locations, nothing happens. The other study tables on other pages all work fine.

**Comment by skept** [comment]
@tyarkoni It looks like this only happens in the production server but not in my dev environment nor the test server. I was having a similar issue reproducing #80. I'm looking into it.

**Comment by tyarkoni** [comment]
Oh, then I think I know what the issue might be. There's some weird problem where the minified CSS doesn't get recompiled properly by the asset pipeline, and I have to delete the old file manually to get it to update. Should figure out what's going on there. Will let you know if that doesn't solve it.

**Comment by skept** [comment]
@tyarkoni I fixed another issue that was contributing to this too. Can you pull the latest on the analysis branch and see if it's working? Yes, please make sure the latest coffeescript code is getting picked up by the asset pipeline. The locations page is cached - I had to disable caching in my dev environment to get the javascript files to refresh.

**Comment by tyarkoni** [comment]
Yep, works now--closing this!
